(ns turvata.keys
  (:require
   [taoensso.truss :refer [have]])
  (:import
   (java.util Base64 Base64$Encoder)
   (java.nio.charset StandardCharsets)
   (java.security MessageDigest SecureRandom)))

(set! *warn-on-reflection* true)

;;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; helpers

(def ^:private ^SecureRandom
  secure-random (SecureRandom.))

(def ^:private ^Base64$Encoder
  b64-encoder (.withoutPadding (Base64/getUrlEncoder)))

(defn- bytes->b64-str
  ^String [^bytes byte-arr]
  (.encodeToString b64-encoder byte-arr))

(defn- gen-nonce
  "Generate a random nonce of size `bytes`."
  ^bytes [^long bytes]
  (let [nonce (byte-array bytes)]
    (.nextBytes secure-random nonce)
    nonce))

;;; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; public API

(defn hash-token
  "Hash a bearer token for storage in a catalog.

  Security note: this assumes tokens are high-entropy random secrets (e.g.
  generated by `generate-token`), not user-chosen strings."
  [^String token!!]
  (have string? token!!)

  (let [md (MessageDigest/getInstance "SHA-256")
        bytes (.getBytes token!! StandardCharsets/UTF_8)]
    (bytes->b64-str (.digest md bytes))))

(defn generate-token
  "Create a new high-entropy token.

  Returns a map with
  - `:token!!` the token as a string
  - `:hashed` the hashed value to place in the catalog"
  []
  (let [randomdata (gen-nonce 32)
        token      (bytes->b64-str randomdata)
        hashed     (hash-token token)]
    {:token!! token
     :hashed  hashed}))

(defn ^:deprecated random-token
  "Deprecated name for `generate-token` kept for compatibility."
  []
  (generate-token))
